application:
  port: 8000
  base_url: "http://127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  username: "max"
  password: ""
  database_name: "tutorial__zero2prod"
email_client:
  base_url: "localhost"
  sender_email: "test@mail.com"
  authorization_token: "secret"
  timeout_milliseconds: 10000